name: reveriehouse
favicon: null
layout_spectrum: 0.8818504011724144
typography_spectrum: 0.0576755132060498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9212200578767806
  lightness: 0.44852350326254964
  saturation: 0.005187703995034099
  rhythmicContrast: 0.6463543297722936
purpose: []
